project "AssImp"
    kind "StaticLib"  
    language "C++"
    cppdialect "c++17"

	-- Isard is here to fix, I've been notified --

	targetdir ("bin/" .. outputdir .. "/%{prj.name}")
	objdir ("bin-int/" .. outputdir .. "/%{prj.name}")
	
	includedirs
	{
		"include",
		"build/include",
		"code",
		"contrib/unzip",
		"contrib/irrXML",
		"contrib/openddlparser/include",
		"contrib/rapidjson/include",
		"",
		"build"
	}

	files
	{
		"code/Common/Assimp.cpp",
		"code/CApi/CInterfaceIOWrapper.cpp",
		"code/Common/BaseImporter.cpp",
		"code/Common/BaseProcess.cpp",
		"code/Common/PostStepRegistry.cpp",
		"code/Common/ImporterRegistry.cpp",--
		"code/Common/DefaultIOStream.cpp",
		"code/Common/DefaultIOSystem.cpp",
		"code/Common/ZipArchiveIOSystem.cpp",
		"code/Common/Importer.cpp",
		"code/Common/SGSpatialSort.cpp",
		"code/Common/VertexTriangleAdjacency.cpp",
		"code/Common/SpatialSort.cpp",
		"code/Common/SceneCombiner.cpp",
		"code/Common/ScenePreprocessor.cpp",
		"code/Common/SkeletonMeshBuilder.cpp",
		"code/Common/SplitByBoneCountProcess.cpp",
		"code/Common/StandardShapes.cpp",
		"code/Common/TargetAnimation.cpp",
		"code/Common/RemoveComments.cpp",
		"code/Common/Subdivision.cpp",
		"code/Common/scene.cpp",
		"code/Common/Bitmap.cpp",
		"code/Common/Version.cpp",
		"code/Common/CreateAnimMesh.cpp",
		"code/Common/simd.cpp",
		"code/Common/DefaultLogger.cpp",
		"code/Common/Exporter.cpp",
		"code/CApi/AssimpCExport.cpp",
		"code/PostProcessing/CalcTangentsProcess.cpp",
		"code/PostProcessing/ComputeUVMappingProcess.cpp",
		"code/PostProcessing/ConvertToLHProcess.cpp",
		"code/PostProcessing/EmbedTexturesProcess.cpp",
		"code/PostProcessing/FindDegenerates.cpp",
		"code/PostProcessing/FindInstancesProcess.cpp",
		"code/PostProcessing/FindInvalidDataProcess.cpp",
		"code/PostProcessing/FixNormalsStep.cpp",
		"code/PostProcessing/DropFaceNormalsProcess.cpp",
		"code/PostProcessing/GenFaceNormalsProcess.cpp",
		"code/PostProcessing/GenVertexNormalsProcess.cpp",
		"code/PostProcessing/PretransformVertices.cpp",
		"code/PostProcessing/ImproveCacheLocality.cpp",
		"code/PostProcessing/JoinVerticesProcess.cpp",
		"code/PostProcessing/LimitBoneWeightsProcess.cpp",
		"code/PostProcessing/RemoveRedundantMaterials.cpp",
		"code/PostProcessing/RemoveVCProcess.cpp",
		"code/PostProcessing/SortByPTypeProcess.cpp",
		"code/PostProcessing/SplitLargeMeshes.cpp",
		"code/PostProcessing/TextureTransform.cpp",
		"code/PostProcessing/TriangulateProcess.cpp",
		"code/PostProcessing/ValidateDataStructure.cpp",
		"code/PostProcessing/OptimizeGraph.cpp",
		"code/PostProcessing/OptimizeMeshes.cpp",
		"code/PostProcessing/DeboneProcess.cpp",
		"code/PostProcessing/ProcessHelper.cpp",
		"code/PostProcessing/MakeVerboseFormat.cpp",
		"code/PostProcessing/ScaleProcess.cpp",
		"code/PostProcessing/GenBoundingBoxesProcess.cpp",
		"code/Material/MaterialSystem.cpp",
		"code/Importer/STEPParser/STEPFileReader.cpp",
		"code/Importer/STEPParser/STEPFileEncoding.cpp",
		"code/AMF/AMFImporter.cpp",
		"code/AMF/AMFImporter_Geometry.cpp",
		"code/AMF/AMFImporter_Material.cpp",
		"code/AMF/AMFImporter_Postprocess.cpp",
		"code/3DS/3DSConverter.cpp",
		"code/3DS/3DSLoader.cpp",
		"code/AC/ACLoader.cpp",
		"code/ASE/ASELoader.cpp",
		"code/ASE/ASEParser.cpp",
		"code/Assbin/AssbinLoader.cpp",
		"code/B3D/B3DImporter.cpp",
		"code/BVH/BVHLoader.cpp",
		"code/Collada/ColladaLoader.cpp",
		"code/Collada/ColladaParser.cpp",
		"code/DXF/DXFLoader.cpp",
		"code/CSM/CSMLoader.cpp",
		"code/HMP/HMPLoader.cpp",
		"code/Irr/IRRMeshLoader.cpp",
		"code/Irr/IRRShared.cpp",
		"code/Irr/IRRLoader.cpp",
		"code/LWO/LWOAnimation.cpp",
		"code/LWO/LWOBLoader.cpp",
		"code/LWO/LWOLoader.cpp",
		"code/LWO/LWOMaterial.cpp",
		"code/LWS/LWSLoader.cpp",
		"code/MD2/MD2Loader.cpp",
		"code/MD3/MD3Loader.cpp",
		"code/MD5/MD5Loader.cpp",
		"code/MD5/MD5Parser.cpp",
		"code/MDC/MDCLoader.cpp",
		"code/MDL/MDLLoader.cpp",
		"code/MDL/MDLMaterialLoader.cpp",
		"code/NFF/NFFLoader.cpp",
		"code/NDO/NDOLoader.cpp",
		"code/OFF/OFFLoader.cpp",
		"code/Obj/ObjFileImporter.cpp",
		"code/Obj/ObjFileMtlImporter.cpp",
		"code/Obj/ObjFileParser.cpp",
		"code/Ogre/OgreImporter.cpp",
		"code/Ogre/OgreStructs.cpp",
		"code/Ogre/OgreBinarySerializer.cpp",
		"code/Ogre/OgreXmlSerializer.cpp",
		"code/Ogre/OgreMaterial.cpp",
		"code/OpenGEX/OpenGEXImporter.cpp",
		"code/Ply/PlyLoader.cpp",
		"code/Ply/PlyParser.cpp",
		"code/MS3D/MS3DLoader.cpp",
		"code/COB/COBLoader.cpp",
		"code/Blender/BlenderLoader.cpp",
		"code/Blender/BlenderDNA.cpp",
		"code/Blender/BlenderScene.cpp",
		"code/Blender/BlenderModifier.cpp",
		"code/Blender/BlenderBMesh.cpp",
		"code/Blender/BlenderTessellator.cpp",
		"code/Blender/BlenderCustomData.cpp",
		"code/Importer/IFC/IFCLoader.cpp",
		"code/Importer/IFC/IFCReaderGen1_2x3.cpp",
		"code/Importer/IFC/IFCReaderGen2_2x3.cpp",
		"code/Importer/IFC/IFCUtil.cpp",
		"code/Importer/IFC/IFCGeometry.cpp",
		"code/Importer/IFC/IFCMaterial.cpp",
		"code/Importer/IFC/IFCProfile.cpp",
		"code/Importer/IFC/IFCCurve.cpp",
		"code/Importer/IFC/IFCBoolean.cpp",
		"code/Importer/IFC/IFCOpenings.cpp",
		"code/XGL/XGLLoader.cpp",
		"code/FBX/FBXImporter.cpp",
		"code/FBX/FBXParser.cpp",
		"code/FBX/FBXTokenizer.cpp",
		"code/FBX/FBXConverter.cpp",
		"code/FBX/FBXUtil.cpp",
		"code/FBX/FBXDocument.cpp",
		"code/FBX/FBXProperties.cpp",
		"code/FBX/FBXMeshGeometry.cpp",
		"code/FBX/FBXMaterial.cpp",
		"code/FBX/FBXModel.cpp",
		"code/FBX/FBXAnimation.cpp",
		"code/FBX/FBXNodeAttribute.cpp",
		"code/FBX/FBXDeformer.cpp",
		"code/FBX/FBXBinaryTokenizer.cpp",
		"code/FBX/FBXDocumentUtil.cpp",
		"code/Q3D/Q3DLoader.cpp",
		"code/Q3BSP/Q3BSPFileParser.cpp",
		"code/Q3BSP/Q3BSPFileImporter.cpp",
		"code/Raw/RawLoader.cpp",
		"code/SIB/SIBImporter.cpp",
		"code/SMD/SMDLoader.cpp",
		"code/STL/STLLoader.cpp",
		"code/Terragen/TerragenLoader.cpp",
		"code/Unreal/UnrealLoader.cpp",
		"code/X/XFileImporter.cpp",
		"code/X/XFileParser.cpp",
		"code/X3D/X3DImporter.cpp",
		"code/X3D/X3DImporter_Geometry2D.cpp",
		"code/X3D/X3DImporter_Geometry3D.cpp",
		"code/X3D/X3DImporter_Group.cpp",
		"code/X3D/X3DImporter_Light.cpp",
		"code/X3D/X3DImporter_Metadata.cpp",
		"code/X3D/X3DImporter_Networking.cpp",
		"code/X3D/X3DImporter_Postprocess.cpp",
		"code/X3D/X3DImporter_Rendering.cpp",
		"code/X3D/X3DImporter_Shape.cpp",
		"code/X3D/X3DImporter_Texturing.cpp",
		"code/X3D/FIReader.cpp",
		"code/X3D/X3DVocabulary.cpp",
		"code/glTF/glTFImporter.cpp",
		"code/glTF2/glTF2Importer.cpp",
		"code/3MF/D3MFImporter.cpp",
		"code/3MF/D3MFOpcPackage.cpp",
		"code/MMD/MMDImporter.cpp",
		"code/MMD/MMDPmxParser.cpp",
		"code/Importer/StepFile/StepFileImporter.cpp",
		"code/Importer/StepFile/StepFileGen1.cpp",
		"code/Importer/StepFile/StepFileGen2.cpp",
		"code/Importer/StepFile/StepFileGen3.cpp",
		"code/3DS/3DSExporter.cpp",
		"code/Assbin/AssbinExporter.cpp",
		"code/Assxml/AssxmlExporter.cpp",
		"code/Collada/ColladaExporter.cpp",
		"code/Obj/ObjExporter.cpp",
		"code/OpenGEX/OpenGEXExporter.cpp",
		"code/Ply/PlyExporter.cpp",
		"code/FBX/FBXExporter.cpp",
		"code/FBX/FBXExportNode.cpp",
		"code/FBX/FBXExportProperty.cpp",
		"code/STL/STLExporter.cpp",
		"code/X/XFileExporter.cpp",
		"code/X3D/X3DExporter.cpp",
		"code/glTF/glTFExporter.cpp",
		"code/glTF2/glTF2Exporter.cpp",
		"code/3MF/D3MFExporter.cpp",
		"code/Assjson/cencode.c",
		"code/Assjson/json_exporter.cpp",
		"code/Assjson/mesh_splitter.cpp",
		"code/Step/StepExporter.cpp",
		"contrib/unzip/ioapi.c",
		"contrib/unzip/unzip.c",
		"contrib/poly2tri/poly2tri/common/shapes.cc",
		"contrib/poly2tri/poly2tri/sweep/advancing_front.cc",
		"contrib/poly2tri/poly2tri/sweep/cdt.cc",
		"contrib/poly2tri/poly2tri/sweep/sweep.cc",
		"contrib/poly2tri/poly2tri/sweep/sweep_context.cc",
		"contrib/clipper/clipper.cpp",
		"contrib/openddlparser/code/OpenDDLParser.cpp",
		"contrib/openddlparser/code/DDLNode.cpp",
		"contrib/openddlparser/code/OpenDDLCommon.cpp",
		"contrib/openddlparser/code/OpenDDLExport.cpp",
		"contrib/openddlparser/code/Value.cpp",
		"contrib/openddlparser/code/OpenDDLStream.cpp",
		"contrib/irrXML/irrXML.cpp",
		"code/C4D/C4DImporter.cpp",
		"contrib/zip/src/zip.c",
		"contrib/zlib/adler32.c",
		"contrib/zlib/compress.c",
		"contrib/zlib/crc32.c",
		"contrib/zlib/deflate.c",
		"contrib/zlib/gzclose.c",
		"contrib/zlib/gzlib.c",
		"contrib/zlib/gzread.c",
		"contrib/zlib/gzwrite.c",
		"contrib/zlib/inflate.c",
		"contrib/zlib/infback.c",
		"contrib/zlib/inftrees.c",
		"contrib/zlib/inffast.c",
		"contrib/zlib/trees.c",
		"contrib/zlib/uncompr.c",
		"contrib/zlib/zutil.c",
	}

    filter "system:macosx"
		systemversion "latest"
		staticruntime "On"

		defines
		{
			"ASSIMP_BUILD_NO_C4D_IMPORTER"
		}

	filter "system:windows"
		systemversion "latest"

	filter "configurations:Debug"
		defines "SW_DEBUG"
		runtime "Debug"
		symbols "on"

	filter "configurations:Release"
		defines "SW_RELEASE"
		runtime "Release"
		optimize "on"

	filter "configurations:Dist"
		defines "SW_DIST"
		runtime "Release"
		optimize "on"